# Generated by Django 5.1.2 on 2024-10-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webscan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="content",
            field=models.TextField(help_text="存储报告内容"),
        ),
        migrations.AlterField(
            model_name="report",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="自动添加创建时间"),
        ),
        migrations.AlterField(
            model_name="scan",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="自动添加创建时间"),
        ),
        migrations.AlterField(
            model_name="scan",
            name="results",
            field=models.JSONField(
                blank=True, default=dict, help_text="存储扫描结果（可选），默认为空字典", null=True
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="scan_type",
            field=models.CharField(
                choices=[("quick", "快速扫描"), ("deep", "深度扫描")],
                default="quick",
                help_text="选择扫描类型：快速扫描或深度扫描",
                max_length=50,
                verbose_name="扫描类型",
            ),
        ),
        migrations.AlterField(
            model_name="scan",
            name="url",
            field=models.URLField(help_text="存储目标URL，确保唯一性", unique=True),
        ),
    ]
