# Generated by Django 5.1.2 on 2024-11-08 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0002_alter_report_content_alter_report_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(help_text='扫描目标网址', max_length=255)),
                ('scan_type', models.CharField(help_text='扫描类型，如快速、深度等', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('low_vulns', models.PositiveIntegerField(default=0, help_text='低风险漏洞数')),
                ('medium_vulns', models.PositiveIntegerField(default=0, help_text='中风险漏洞数')),
                ('high_vulns', models.PositiveIntegerField(default=0, help_text='高风险漏洞数')),
                ('total_vulns', models.PositiveIntegerField(default=0, help_text='总漏洞数')),
                ('scanned_pages', models.PositiveIntegerField(default=0, help_text='已扫描页面数')),
                ('total_pages', models.PositiveIntegerField(default=0, help_text='总页面数')),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Scan',
        ),
    ]
