# Generated by Django 5.1.2 on 2024-11-11 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0003_scantask_delete_report_delete_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='scantask',
            name='scan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='扫描任务ID'),
        ),
        migrations.AddField(
            model_name='scantask',
            name='target_id',
            field=models.IntegerField(blank=True, help_text='目标ID', null=True),
        ),
    ]
