# Generated by Django 5.1.2 on 2024-11-13 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0004_scantask_scan_id_scantask_target_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scantask',
            name='target_id',
        ),
    ]
