# Generated by Django 5.1.2 on 2024-11-16 15:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0005_remove_scantask_target_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scantask',
            name='id',
        ),
        migrations.AlterField(
            model_name='scantask',
            name='scan_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='扫描任务ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scantask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=50),
        ),
        migrations.CreateModel(
            name='ScanResults',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='扫描结果ID', primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='扫描页面URL', max_length=255)),
                ('vulnerability_name', models.CharField(help_text='漏洞名称', max_length=255)),
                ('severity', models.CharField(help_text='漏洞等级', max_length=50)),
                ('description', models.TextField(help_text='漏洞描述')),
                ('found_at', models.DateTimeField(help_text='发现时间')),
                ('scan_id', models.ForeignKey(help_text='扫描任务ID', on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='webscan.scantask')),
            ],
        ),
    ]
