# Generated by Django 5.1.2 on 2024-11-18 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0006_remove_scantask_id_alter_scantask_scan_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scanresults',
            old_name='found_at',
            new_name='discovery_time',
        ),
    ]
