# Generated by Django 5.1.2 on 2024-11-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0007_rename_found_at_scanresults_discovery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresults',
            name='request_input',
            field=models.CharField(default='', help_text='请求输入', max_length=100),
        ),
        migrations.AddField(
            model_name='scanresults',
            name='response_status_code',
            field=models.IntegerField(default=0, help_text='响应状态码'),
        ),
    ]
