# Generated by Django 5.1.2 on 2024-11-21 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0010_alter_scantask_target_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scantask',
            old_name='target_url',
            new_name='target_str',
        ),
    ]
