# Generated by Django 5.1.2 on 2024-11-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webscan', '0011_rename_target_url_scantask_target_str'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scantask',
            old_name='target_str',
            new_name='target_url',
        ),
    ]
